In [1]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("SaratogaHouses.csv")

In [3]:
X = dataset['livingArea'].values
y =dataset ['price'].values

In [4]:
X[:10]

array([ 906, 1953, 1944, 1944,  840, 1152, 2752, 1662, 1632, 1416],
      dtype=int64)

In [5]:
X = X.reshape(-1,1)

In [6]:
reg = LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
y_pred = reg.predict(X)

In [8]:
print(y[:10])
print(y_pred[:10])

[132500 181115 109000 155000  86060 120000 153000 170000  90000 122900]
[115928.4169181  234367.71823171 233349.61535509 233349.61535509
 108462.32915621 143756.56221241 324752.62916731 201449.05855429
 198055.38229888 173620.91325997]


In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [11]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1382, 1)
(1382,)
(346, 1)
(346,)


In [12]:
print(X.shape)
print(y.shape)

(1728, 1)
(1728,)


In [13]:
reg_2 = LinearRegression()
reg_2.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
y_pred = reg_2.predict(x_test)

In [15]:
print(y_pred)

[194169.21861406 385339.6889083  116801.40475381 184273.33544589
 195068.84435662 191695.24782202 184273.33544589 201816.03742583
 239600.3186134  252532.43866271 117251.21762509 144239.98990192
 147388.68000089 316068.50673109 246347.51168261 228354.99683138
 136143.35821887 297626.17900859 318542.47752314 339233.86960204
 375443.80574013 239150.50574212 381178.91984895 178200.8616836
 202715.66316839 129733.52480312 279858.57059301 182474.08396077
 159758.5339611  246797.32455389 322140.98049338 332711.58296847
 211824.37381182 391074.80301712 312470.00376085 166280.82059467
 460908.25128343 119162.92232803 214185.89138605 117251.21762509
 189895.9963369  119950.09485277 171228.76217875 294252.58247399
 230379.15475215 117251.21762509 169317.05747581 148288.30574345
 119950.09485277 202265.85029711 352953.1621761  239600.3186134
 133444.48099119 222394.97628692 209125.49658414 218459.11366321
 221157.9908909  262765.68148435 316743.22603801 220258.36514833
 189333.7302478  114102.527

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
mse = mean_squared_error(y_test,y_pred)

In [18]:
rmse = np.sqrt(mse)

In [19]:
print("ROOT MEAN SQUARE", rmse)

ROOT MEAN SQUARE 68364.88895573685


In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
std = StandardScaler()

In [22]:
X = std.fit_transform(X)

C:\Users\hp\Anaconda3\envs\mlcc\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\envs\mlcc\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [23]:
X[:10]

array([[-1.36985441],
       [ 0.31951971],
       [ 0.30499787],
       [ 0.30499787],
       [-1.47634791],
       [-0.9729241 ],
       [ 1.60873645],
       [-0.1500198 ],
       [-0.19842594],
       [-0.54695011]])

In [24]:
y = y.reshape(-1,1)

In [25]:
y = std.fit_transform(y)

C:\Users\hp\Anaconda3\envs\mlcc\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\envs\mlcc\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [26]:
y[:10]

array([[-0.80748259],
       [-0.31349249],
       [-1.04627242],
       [-0.57885403],
       [-1.27937193],
       [-0.93449845],
       [-0.59917657],
       [-0.42643499],
       [-1.23933653],
       [-0.90503077]])

In [27]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [28]:
reg_3 = LinearRegression()

In [29]:
reg_3.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [30]:
y_pred = reg_3.predict(x_test)

In [31]:
mse = mean_squared_error(y_test,y_pred)

In [32]:
rmse = np.sqrt(mse)

In [33]:
print(rmse)

0.6463412969752008


In [34]:
print(y_pred[:10])

[[-0.1021949 ]
 [-0.3111251 ]
 [ 0.56821849]
 [ 0.23071586]
 [ 0.71745435]
 [ 0.92868048]
 [-0.74850095]
 [-0.32375274]
 [-0.72898549]
 [ 0.11591905]]
