##### 1) Armstrong Number

In [1]:
num = int(input("Enter a number "))
count = 0
temp = num
while (temp > 0):
   letter = temp % 10
   count = count + letter ** 3
   temp = temp // 10

if (num == count):
   print("It is an Armstrong number")
else:
   print("Not an Armstrong number")

Enter a number 371
It is an Armstrong number


##### 2) Armstrong Number in Series

In [2]:
def armstrong(n):
    count = 0
    temp = n
    while (temp > 0):
        letter = temp % 10
        count = count + letter ** 3
        temp = temp // 10
        
    if(n == count):
        return True
    else:
        return False

no = int(input("Enter a final number: "))
for i in range(0, no):
    if(armstrong(i) == True):
        print(i)

Enter a final number: 300
0
1
153


##### 3) Sum of Natural Numbers

In [3]:
initial = int(input("Enter a initial number: "))
final = int(input("Enter a final number: "))

sum = 0

for i in range(initial, final + 1):
    sum += i
print(sum)

Enter a initial number: 10
Enter a final number: 20
165


##### 4) Factorial of a number

In [4]:
fact_num = int(input("Enter a number: "))
fact = 1

for i in range(1, fact_num + 1):
    fact *= i
print(fact)

Enter a number: 5
120


##### 5) Multiplication Table

In [5]:
mul_num = int(input("Enter multiplicative number: "))
fin_num = int(input("Enter final number: "))

for i in range(0, fin_num + 1):
    print(mul_num, "X", i, "=", mul_num * i)

Enter multiplicative number: 10
Enter final number: 10
10 X 0 = 0
10 X 1 = 10
10 X 2 = 20
10 X 3 = 30
10 X 4 = 40
10 X 5 = 50
10 X 6 = 60
10 X 7 = 70
10 X 8 = 80
10 X 9 = 90
10 X 10 = 100


In [5]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a**2)
print(a*2)
print(a**b)
a.sum()
a.mean()

[5 7 9]
[1 4 9]
[2 4 6]
[  1  32 729]


2.0

##### Wave Form

In [7]:
def WaveForm(a, n):  
    for i in range(0, n, 2): 
        if (i> 0 and a[i] < a[i-1]): 
            (a[i],a[i-1]) = (a[i-1],a[i]) 
        if (i < n-1 and a[i] < a[i+1]): 
            (a[i],a[i+1]) = (a[i+1],a[i]) 
  
a = [1, 2, 3, 4, 5, 6, 7] 
WaveForm(a, len(a)) 
print(a)

[2, 1, 4, 3, 6, 5, 7]


In [18]:
a = np.zeros(10, int)
print(a)
a1 = np.ones(10, int)
print(a1)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


In [23]:
l = [(1, 5), (6, 45), (3, 2)]
print(l[0][0])
l.sort()
print(l)
print(l.count(1))
l.reverse()

1
[(1, 5), (3, 2), (6, 45)]
0


##### Pandas

In [2]:
import pandas as pd

In [3]:
arc = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv")
print(type(arc))

<class 'pandas.core.frame.DataFrame'>


In [4]:
df = arc.copy()
df.head(10)

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5  8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
6  8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
7  8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
8  8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
9  7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0

In [5]:
print(df.shape)

(517, 13)


In [6]:
print(df.dtypes)

X          int64
Y          int64
month     object
day       object
FFMC     float64
DMC      float64
DC       float64
ISI      float64
temp     float64
RH         int64
wind     float64
rain     float64
area     float64
dtype: object


In [7]:
df.describe()

X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663   
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477   
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000   
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000   
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000   
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000   
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000   

             temp          RH        wind        rain         area  
count  517.000000  517.000000  517.000000  517.000000   517.000000  
mean    18.889168   44.288201    4.017602    0.021663    12.847292  
std      5.806625   16.317469    1.791653    0.295959    63.655818  
min      2.200000   15.000000    0.400000    0.000000     0.000000  
25%     15.500000   33.000000    2.700000    0.000000     0.000000  
50%     19.300000   42.000000    4.000000    0.000000     0.520000  
75%     22.800000   53.000000    4.900000    0.000000     6.570000  
max     33.300000  100.000000    9.400000    6.400000  1090.840000

In [8]:
df.X

0      7
1      7
2      7
3      8
4      8
5      8
6      8
7      8
8      8
9      7
10     7
11     7
12     6
13     6
14     6
15     6
16     5
17     8
18     6
19     6
20     6
21     5
22     7
23     7
24     7
25     7
26     7
27     7
28     6
29     6
      ..
487    5
488    4
489    4
490    4
491    4
492    1
493    1
494    6
495    6
496    4
497    3
498    6
499    7
500    8
501    7
502    4
503    2
504    4
505    1
506    1
507    2
508    1
509    5
510    6
511    8
512    4
513    2
514    7
515    1
516    6
Name: X, Length: 517, dtype: int64

In [9]:
df.isnull()

X      Y  month    day   FFMC    DMC     DC    ISI   temp     RH  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
5    False  False  False  False  False  False  False  False  False  False   
6    False  False  False  False  False  False  False  False  False  False   
7    False  False  False  False  False  False  False  False  False  False   
8    False  False  False  False  False  False  False  False  False  False   
9    False  False  False  False  False  False  False  False  False  False   
10   False  False  False  False  False  False  False  False  False  False   
11   False  False  False  False  False  False  False  False  False  False   
12   False  False  False  False  False  False  False  False  False  False   
13   False  False  False  False  False  False  False  False  False  False   
14   False  False  False  False  False  False  False  False  False  False   
15   False  False  False  False  False  False  False  False  False  False   
16   False  False  False  False  False  False  False  False  False  False   
17   False  False  False  False  False  False  False  False  False  False   
18   False  False  False  False  False  False  False  False  False  False   
19   False  False  False  False  False  False  False  False  False  False   
20   False  False  False  False  False  False  False  False  False  False   
21   False  False  False  False  False  False  False  False  False  False   
22   False  False  False  False  False  False  False  False  False  False   
23   False  False  False  False  False  False  False  False  False  False   
24   False  False  False  False  False  False  False  False  False  False   
25   False  False  False  False  False  False  False  False  False  False   
26   False  False  False  False  False  False  False  False  False  False   
27   False  False  False  False  False  False  False  False  False  False   
28   False  False  False  False  False  False  False  False  False  False   
29   False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
487  False  False  False  False  False  False  False  False  False  False   
488  False  False  False  False  False  False  False  False  False  False   
489  False  False  False  False  False  False  False  False  False  False   
490  False  False  False  False  False  False  False  False  False  False   
491  False  False  False  False  False  False  False  False  False  False   
492  False  False  False  False  False  False  False  False  False  False   
493  False  False  False  False  False  False  False  False  False  False   
494  False  False  False  False  False  False  False  False  False  False   
495  False  False  False  False  False  False  False  False  False  False   
496  False  False  False  False  False  False  False  False  False  False   
497  False  False  False  False  False  False  False  False  False  False   
498  False  False  False  False  False  False  False  False  False  False   
499  False  False  False  False  False  False  False  False  False  False   
500  False  False  False  False  False  False  False  False  False  False   
501  False  False  False  False  False  False  False  False  False  False   
502  False  False  False  False  False  False  False  False  False  False   
503  False  False  False  False  False  False  False  False  False  False   
504  False  False  False  False  False  False  False  False  False  False   
505  False  False  False  False  False  False  False  False  False  False   
506  False  False  False  False  False  False  False  False  False  False   
507  

In [10]:
df.isnull().sum()

X        0
Y        0
month    0
day      0
FFMC     0
DMC      0
DC       0
ISI      0
temp     0
RH       0
wind     0
rain     0
area     0
dtype: int64

In [11]:
df.iloc[1:4, 2:4]

month  day
1   oct  tue
2   oct  sat
3   mar  fri

In [12]:
df.tail()

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

In [13]:
df[df.X<2]

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain    area
77   1  3   mar  mon  87.6   52.2  103.8   5.0   8.3  72   3.1   0.0    0.00
78   1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   0.0    0.00
79   1  2   aug  tue  91.0  121.2  561.6   7.0  21.6  19   6.7   0.0    0.00
80   1  2   aug  sun  91.4  142.4  601.4  10.6  19.5  39   6.3   0.0    0.00
81   1  2   aug  sun  90.2   99.6  631.2   6.3  17.9  44   2.2   0.0    0.00
82   1  2   aug  tue  94.8  108.3  647.1  17.0  18.6  51   4.5   0.0    0.00
83   1  2   aug  wed  92.1  111.2  654.1   9.6  16.6  47   0.9   0.0    0.00
84   1  2   aug  thu  91.7  114.3  661.3   6.3  20.2  45   3.6   0.0    0.00
85   1  2   sep  thu  92.9  137.0  706.4   9.2  21.5  15   0.9   0.0    0.00
86   1  2   sep  thu  92.9  137.0  706.4   9.2  25.4  27   2.2   0.0    0.00
87   1  2   sep  thu  92.9  137.0  706.4   9.2  22.4  34   2.2   0.0    0.00
88   1  2   sep  sun  93.5  149.3  728.6   8.1  25.3  36   3.6   0.0    0.00
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0    0.43
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0    0.55
143  1  2   jul  sat  90.0   51.3  296.3   8.7  16.6  53   5.4   0.0    0.71
154  1  5   sep  sat  93.4  145.4  721.4   8.1  29.6  27   2.7   0.0    1.46
174  1  4   aug  sat  90.2   96.9  624.2   8.9  14.2  53   1.8   0.0    3.50
175  1  4   aug  sat  90.2   96.9  624.2   8.9  20.3  39   4.9   0.0    4.53
180  1  3   sep  sun  92.4  124.1  680.7   8.5  23.9  32   6.7   0.0    5.33
187  1  5   sep  mon  90.9  126.5  686.5   7.0  21.0  42   2.2   0.0    7.30
200  1  5   sep  tue  91.0  129.5  692.6   7.0  21.6  33   2.2   0.0   11.53
217  1  3   sep  mon  88.6   91.8  709.9   7.1  12.4  73   6.3   0.0   30.32
231  1  5   sep  sun  93.5  149.3  728.6   8.1  27.8  27   3.1   0.0   95.18
237  1  2   sep  tue  91.0  129.5  692.6   7.0  18.8  40   2.2   0.0  212.88
305  1  4   sep  sun  89.6   84.1  714.3   5.7  19.0  52   2.2   0.0    0.00
321  1  4   sep  thu  92.8  119.0  783.5   7.5  16.8  28   4.0   0.0    7.21
325  1  4   sep  sat  92.2  102.3  751.5   8.4  24.2  27   3.1   0.0    0.00
333  1  4   sep  mon  92.1   87.7  721.1   9.5  18.1  54   3.1   0.0    2.13
346  1  4   sep  mon  91.5  130.1  807.1   7.5  21.3  35   2.2   0.0   28.19
359  1  4   sep  fri  92.5  122.0  789.7  10.2  21.1  39   2.2   0.0    8.12
392  1  3   sep  sun  91.0  276.3  825.1   7.1  21.9  43   4.0   0.0   70.76
398  1  2   aug  sat  93.7  231.1  715.1   8.4  25.9  32   3.1   0.0    0.00
409  1  4   jul  tue  92.3   96.2  450.2  12.1  23.4  31   5.4   0.0    0.00
423  1  3   sep  sat  91.2   94.3  744.4   8.4  22.3  48   4.0   0.0    0.72
428  1  3   aug  thu  94.8  222.4  698.6  13.9  26.2  34   5.8   0.0    0.00
431  1  3   aug  sat  92.1  178.0  605.3   9.6  23.3  40   4.0   0.0    6.36
434  1  4   aug  fri  90.6  269.8  811.2   5.5  22.2  45   3.6   0.0    0.00
439  1  3   sep  fri  91.1   91.3  738.1   7.2  19.1  46   2.2   0.0    0.33
443  1  2   jul  fri  90.7   80.9  368.3  16.8  14.8  78   8.0   0.0    0.00
451  1  4   aug  fri  90.5  196.8  649.9  16.3  11.8  88   4.9   0.0    9.71
457  1  4   aug  wed  91.7  191.4  635.9   7.8  19.9  50   4.0   0.0   82.75
462  1  4   sep  sun  91.0  276.3  825.1   7.1  14.5  76   7.6   0.0    3.71
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0    0.00
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0   43.32
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0    5.80
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0    0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0    0.00
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0    0.00

In [14]:
df.reset_index(drop = True, inplace = True)
df.head(20)

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
0   7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1   7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2   7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3   8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4   8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5   8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
6   8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
7   8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
8   8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
9   7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0
10  7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.0
11  7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.0
12  6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.0
13  6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.0
14  6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.0
15  6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.0
16  5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.0
17  8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.0
18  6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.0
19  6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.0

In [16]:
df.drop('month', axis = 1, inplace = True)
df

X  Y  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4  wed  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4  thu  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6  mon  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3  sun 