In [1]:
import numpy as np

In [2]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
#no hidden layer
weights=np.random.random([2,1])-1
bias=2*np.random.random(1)-1
weights,bias

(array([[-0.88507022],
        [-0.82377344]]), array([0.90242996]))

In [5]:
#forward propagation without hidden layer
output0=X
output=sig(np.dot(output0,weights)+bias)
output

array([[0.7114486 ],
       [0.519654  ],
       [0.50433983],
       [0.30865524]])

In [6]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))


In [7]:

first_term=output-Y
input_for_last_layer=np.dot(output0,weights)+ bias
second_term=derivativeSig(input_for_last_layer)
first_two=first_term * second_term
first_two.shape

(4, 1)

In [8]:
#backward propagation without hidden layer
lr=0.0001
for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)* bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term * second_term
    changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0]+=first_two[j][0] * output0[j][i]
    weights= weights- lr * changes

    bias_change=0.0
    for j in range(4):
        bias_change+=first_two[j][0] * 1
    bias=bias-lr* bias_change

output=sig(np.dot(X,weights)+bias)
weights, bias, output

        

(array([[-0.8692824 ],
        [-0.81282555]]), array([0.63771314]), array([[0.65423633],
        [0.45633342],
        [0.44236501],
        [0.2603029 ]]))

In [9]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [10]:
def sig(z):
    return 1/(1+np.exp(-z))

In [11]:
#no hidden layer
weights=np.random.random([2,1])-1
bias=2*np.random.random(1)-1
weights,bias

(array([[-0.01734341],
        [-0.21457669]]), array([0.77795579]))

In [12]:
#forward propagation without hidden layer
output0=X
output=sig(np.dot(output0,weights)+bias)
output

array([[0.68523937],
       [0.63723404],
       [0.68148667],
       [0.63321535]])

In [13]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))


In [14]:

first_term=output-Y
input_for_last_layer=np.dot(output0,weights)+ bias
second_term=derivativeSig(input_for_last_layer)
first_two=first_term * second_term
first_two.shape

(4, 1)

In [30]:
#backward propagation without hidden layer
lr=0.009
for iter in range(1900):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)* bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term * second_term
    changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0]+=first_two[j][0] * output0[j][i]
    weights= weights- lr * changes

    bias_change=0.0
    for j in range(4):
        bias_change+=first_two[j][0] * 1
    bias=bias-lr* bias_change

output=sig(np.dot(X,weights)+bias)
weights, bias, output

        

(array([[2.68923785],
        [2.66850167]]), array([-2.89171235]), array([[0.05256477],
        [0.44442787],
        [0.4495536 ],
        [0.92172561]]))